public with sharing class ContentVersionClassification {

    public static final String TECHNICAL_DESCRIPTION = 'Technical Description';
    public static final String PUBLICATION_MANUSCRIPTS = 'Publication/Manuscripts';
    public static final String SOFTWARE_CODE = 'Software Code';
    public static final String THIRD_PARTY_AGREEMENTS = 'Third Party Agreements';
    public static final String THIRD_PARTY_CODE = 'Third Party Code';
    public static final String SIGNED_DISCLOSURE = 'Signed Disclosure';
    public static final String FINALISED_CRDR = 'Finalised_CRDR';
    public static final String DRAFT_CRDR = 'Draft_CRDR';
    public static final String ORIGINAL_DOCUMENT = 'Original_Document';
    public static final String CORRESPONDENCE = 'Correspondence';
    public static final String LINK = 'Link';
    public static final String AGREEMENT_AMENDMENT = 'Agreement_Amendment';
    public static final String WORKSHEET = 'Worksheet';
    public static final String MEMO_OF_SIGNATORY = 'Memo_of_Signatory';
    public static final String RENEWAL = 'Renewal';
    public static final String TERMINATION = 'Termination';
    public static final String EQUITY = 'Equity';


}