global class DisclosureConditionsWrapper {
    public DisclosureConditionsWrapper() {
    }

    global String emptyOrNotAnsweredText;
    global String recipientId;
    global String isPrimaryInventor;
    global String inventorFullName;
    global String signedByName;
    global String createdDate;
    global String subTypeName;
    global String inventorTypeName;
    global boolean isNonMitSalary;
    global boolean isWorkDoneOutsideMit;
    global boolean isPartOfCollaboration;
    global boolean isConsultantOrContract;
    global string fundingThroughDlcs;
    global string affiliatedWithOrgsDlcs;
    global boolean isPartOfClass;
    global boolean isActiveKerb;
    global boolean isSigned;
    global String tenureFromDate;
    global String tenureToDate;
    global String tenureStartDate;
    global boolean hasWOCorDAPwithVA;
}