global class SoftwareCodeWrapper {
    public SoftwareCodeWrapper() {

    }

    global Software_Code_Disclosure__c softwareCode;

    global boolean isOpenSource;
    global String yearsCodeFirstCreated;
    global String yearsCodeFirstPublished;
    global String partOfEmployment;
    global boolean useThirdPartyCode;
    global boolean softwareDerivativeNonMIT;
    global String sourceOfTrainingData;
}